In [6]:
%reload_ext autoreload
%autoreload 2

import numpy as np
from file_exchange import config
from file_exchange.network import Network
from file_exchange.peers_view import PeersView
from file_exchange.user import User
import gevent
from gevent.pool import Group
from gevent.event import AsyncResult

from datetime import datetime

In [3]:
conf = config.default
conf['n_users'] = 10
conf

{'gossip_size': 20,
 'layer_threshold': 0.001,
 'minimum_node_availability': 0,
 'n_file_chunks': 10,
 'n_layers': 3,
 'n_rounds': 2,
 'n_users': 10,
 'period': datetime.timedelta(0, 1)}

In [ ]:
address_book = PeersView(conf)
net = Network()



In [6]:
address_book = PeersView(conf)
net = Network()
users = [None] * conf['n_users']
for i in range(conf['n_users']):
    users[i] = User(address_book, net, conf)

def output_view(view, conf):
    i = 0
    while True:
        print("Iteration #{} at time {}".format(i, datetime.now().time()))
        print(view.get())
        gevent.sleep(conf['period'].total_seconds())
        i+=1

print("Before spawn")
output_thread = gevent.spawn(output_view, address_book, conf)
print("Before start")
users_threads = Group()
for u in users:
    users_threads.start(u)

print("At join")
users_threads.join()
print("User thread joined")
gevent.kill(output_thread)


Before spawn
Before start
At join
Iteration #0 at time 14:26:11.951946
Empty DataFrame
Columns: [t, addr, type, p]
Index: []
Iteration #1 at time 14:26:12.954658
                                    addr         p                          t  \
2018-04-24 14:26:11.957478  rd839um4b844  0.946199 2018-04-24 14:26:11.957478   
2018-04-24 14:26:11.960589  tbnyg5kyuibm  0.968524 2018-04-24 14:26:11.960589   
2018-04-24 14:26:11.963255  jy8sea87hlyi  0.675647 2018-04-24 14:26:11.963255   
2018-04-24 14:26:11.965781  y54u2zsmfcz2  0.520520 2018-04-24 14:26:11.965781   
2018-04-24 14:26:11.968344  iphuyiww6g0h  0.613303 2018-04-24 14:26:11.968344   
2018-04-24 14:26:11.970938  d3xkzfh4zvpb  0.801017 2018-04-24 14:26:11.970938   
2018-04-24 14:26:11.973483  3qsnfccthrn6  0.890540 2018-04-24 14:26:11.973483   
2018-04-24 14:26:11.975966  cme787w8cilw  0.548230 2018-04-24 14:26:11.975966   
2018-04-24 14:26:11.978424  ep69x1dlnmx3  0.735364 2018-04-24 14:26:11.978424   
2018-04-24 14:26:11.980805  

In [83]:
a = np.array([1, 1, 2, 3, 4, 1, 2])
b = np.zeros(len(a), dtype=np.bool)
b[:3] = True
print(a)
print(b)

not_acked_ids = np.argwhere(b == False).ravel()
print(not_acked_ids)
print(a.argsort())
for x in a.argsort(kind='heapsort'):
    if x in not_acked_ids:
        print(x)
        break
#np.intersect1d(a.argsort(), not_acked_ids, assume_unique=True)

[1 1 2 3 4 1 2]
[ True  True  True False False False False]
[3 4 5 6]
[0 1 5 2 6 3 4]
5


In [84]:
all(a)

True