In [8]:
import numpy as np

A=[[0.5,0.3,0.2],
  [0.1, 0.1, 0.8]]
A=np.array(A, dtype=np.float64)

In [1]:
%reload_ext autoreload
%autoreload 2

from  modules import model

In [61]:
states_name=["Home", "Outside", "Work"]
obs_name=["Phone", "Home computer", "NAS", "Workstation", "Laptop"]
m=model.Model()
m.set(
[[0.5,0.5,0],
 [0.3,0.4,0.3],
 [0,0.5,0.5]],
[[0.9,0.4,0.99,0,0.7],
 [0.9,0,0.99,0,0.2],
 [0.7,0,0.99,0.7,0.3]],
states_name, obs_name)
states,obs=m.sample()
for s, o in zip(states, obs):
    print(states_name[s], [obs_name[i] for i in range(len(obs_name)) if o[i]])

Outside ['Phone', 'NAS']
Outside ['Phone', 'NAS']
Home ['Phone', 'Home computer', 'NAS', 'Laptop']
Home ['Phone', 'NAS', 'Laptop']
Outside ['Phone', 'NAS']
Work ['Phone', 'NAS', 'Laptop']
Work ['Phone', 'NAS']
Outside ['Phone', 'NAS']
Home ['Phone', 'NAS', 'Laptop']
Home ['Phone', 'NAS', 'Laptop']
Home ['Phone', 'NAS', 'Laptop']
Outside ['Phone', 'NAS']
Work ['Phone', 'NAS', 'Workstation', 'Laptop']
Outside ['Phone', 'NAS']
Outside ['Phone', 'NAS']
Outside ['Phone', 'NAS', 'Laptop']
Work ['Phone', 'NAS', 'Workstation']
Outside ['Phone', 'NAS']
Work ['Phone', 'NAS', 'Workstation']
Outside ['Phone', 'NAS']


In [43]:
m.predict(5,1)

array([[ 0.2     ,  0.12    ,  0.      ],
       [ 0.16    ,  0.108   ,  0.06    ],
       [ 0.134   ,  0.1092  ,  0.084   ],
       [ 0.1216  ,  0.10908 ,  0.0966  ],
       [ 0.11534 ,  0.109092,  0.10284 ]])

In [50]:
import numpy as np
n_obs=5

P=[[1/n_obs]*n_obs]*3
P=np.array(P, dtype=np.float64)
print(P)
P[0, 0]=0.3
print(P)

[[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]]
[[ 0.3  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]]


In [64]:
default_m=model.get_default_model(m.observations)
print(default_m.A)
print(default_m.B)
print(default_m.states)
print(default_m.observations)

[[ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]
[[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]]
['Home', 'Outside', 'Work']
['Phone', 'Home computer', 'NAS', 'Workstation', 'Laptop']


In [72]:
states,obs=m.sample(length=100)
print(states)
print(obs)

[1 2 2 2 2 2 1 1 1 2 2 1 1 2 1 0 1 1 1 0 0 1 2 1 2 1 2 2 1 2 1 0 0 0 0 1 2
 1 1 1 0 0 0 1 0 1 0 1 0 1 1 2 1 1 0 0 0 1 0 0 0 1 2 1 1 2 2 2 2 2 2 2 2 2
 1 0 1 2 2 2 1 1 0 1 0 1 1 2 2 1 1 1 1 1 0 1 0 1 0 0]
[[ True False  True False  True]
 [False False  True  True  True]
 [ True False  True  True  True]
 [ True False  True False  True]
 [ True False  True  True  True]
 [ True False  True  True False]
 [ True False  True False False]
 [ True False  True False False]
 [ True False  True False  True]
 [ True False  True  True False]
 [ True False  True False  True]
 [ True False  True False False]
 [ True False  True False False]
 [ True False  True False False]
 [False False  True False  True]
 [False False  True False  True]
 [ True False  True False False]
 [ True False  True False  True]
 [ True False  True False False]
 [ True False  True False False]
 [ True False  True False  True]
 [False False  True False False]
 [ True False  True  True False]
 [ True False  True False  True]
 [ T

In [73]:
[obs_name[i] for i in range(len(obs_name)) for o in obs if o[i]]

['Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Phone',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'Home computer',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS',
 'NAS'

In [56]:
sequence=['zertr', 'ertet', 'rtrtrt', 'ertet', 'ertet', 'rtertsdf', 'fgdfgs']
obs='ertet'
non_obs="non_"+'ertet'

[obs if o == obs else non_obs for o in sequence]

['non_ertet', 'ertet', 'non_ertet', 'ertet', 'ertet', 'non_ertet', 'non_ertet']